# Generated by Django 5.1.6 on 2026-02-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_organiz_16d854_idx',
            old_name='assets_asset_org_name_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_organiz_2c4606_idx',
            old_name='assets_asset_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='configurationitem',
            new_name='assets_conf_organiz_c7514b_idx',
            old_name='assets_ci_org_name_idx',
        ),
        migrations.RenameIndex(
            model_name='configurationitem',
            new_name='assets_conf_organiz_69b45a_idx',
            old_name='assets_ci_org_type_idx',
        ),
    ]
