# Generated by Django 5.1.6 on 2026-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_assets_asset_org_name_idx_assets_asse_organiz_16d854_idx_and_more'),
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='configurationitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asset',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'archived_at'], name='assets_asse_organiz_e66de8_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['organization', 'archived_at'], name='assets_conf_organiz_63dca9_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_assets_asset_org_name_active'),
        ),
        migrations.AddConstraint(
            model_name='configurationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_assets_configitem_org_name_active'),
        ),
    ]
