# Generated by Django 5.1.6 on 2026-02-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_remove_customfield_uniq_core_customfield_org_ct_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibleAssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Optional icon name (UI).', max_length=64)),
                ('color', models.CharField(blank=True, default='', help_text='Optional color token (UI).', max_length=32)),
                ('sort_order', models.IntegerField(default=100)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_asset_types', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FlexibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_assets', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='flexible_assets', to='core.tag')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='flexassets.flexibleassettype')),
            ],
        ),
        migrations.AddIndex(
            model_name='flexibleassettype',
            index=models.Index(fields=['organization', 'archived', 'sort_order', 'name'], name='flexassets__organiz_d10cd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flexibleassettype',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='flexibleasset',
            index=models.Index(fields=['organization', 'asset_type', 'name'], name='flexassets__organiz_fc5639_idx'),
        ),
        migrations.AddIndex(
            model_name='flexibleasset',
            index=models.Index(fields=['organization', 'name'], name='flexassets__organiz_8d8da0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flexibleasset',
            unique_together={('organization', 'asset_type', 'name')},
        ),
    ]
