# Generated by Django 5.1.6 on 2026-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('flexassets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flexibleasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flexibleasset',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='flexibleasset',
            index=models.Index(fields=['organization', 'archived_at'], name='flexassets__organiz_cfe363_idx'),
        ),
        migrations.AddConstraint(
            model_name='flexibleasset',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'asset_type', 'name'), name='uniq_flexassets_asset_org_type_name_active'),
        ),
    ]
