# Generated by Django 5.1.6 on 2026-02-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_rename_core_savedv_organiz_2e2f40_idx_core_savedv_organiz_f27cd3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Domain name, e.g. example.com', max_length=253)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('other', 'Other')], default='active', max_length=16)),
                ('registrar', models.CharField(blank=True, default='', max_length=200)),
                ('dns_provider', models.CharField(blank=True, default='', max_length=200)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='domains', to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, default='', max_length=253)),
                ('subject_alt_names', models.TextField(blank=True, default='', help_text='Comma-separated SANs (optional).')),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=128)),
                ('fingerprint_sha256', models.CharField(blank=True, default='', max_length=128)),
                ('not_before', models.DateField(blank=True, null=True)),
                ('not_after', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='ssl_certificates', to='netapp.domain')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='ssl_certificates', to='core.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organization', 'name'], name='netapp_doma_organiz_86c351_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organization', 'expires_on'], name='netapp_doma_organiz_827405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['organization', 'common_name'], name='netapp_sslc_organiz_8549be_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['organization', 'not_after'], name='netapp_sslc_organiz_1d8399_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['organization', 'fingerprint_sha256'], name='netapp_sslc_organiz_62c2fb_idx'),
        ),
    ]
