# Generated by Django 5.1.6 on 2026-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('netapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='domain',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organization', 'archived_at'], name='netapp_doma_organiz_f518b9_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['organization', 'archived_at'], name='netapp_sslc_organiz_4133be_idx'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_netapp_domain_org_name_active'),
        ),
    ]
