# Generated by Django 5.1.6 on 2026-02-15 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_customfield_flexible_asset_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('domain_expiry', 'Domain expiry'), ('ssl_expiry', 'SSL certificate expiry')], max_length=32)),
                ('audience', models.CharField(choices=[('admins', 'Org admins'), ('all', 'All members')], default='admins', max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('run_interval_minutes', models.IntegerField(default=60, help_text='How often to evaluate this rule.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_ok', models.BooleanField(default=False)),
                ('last_run_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('danger', 'Danger')], default='warn', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('dedupe_key', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflows.workflowrule')),
            ],
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['organization', 'enabled', 'kind', 'updated_at'], name='workflows_w_organiz_4927e7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'user', 'read_at', '-created_at'], name='workflows_n_organiz_e15b41_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'dedupe_key'), name='uniq_workflows_notification_dedupe'),
        ),
    ]
