# Generated by Django 5.1.6 on 2026-02-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrule',
            name='kind',
            field=models.CharField(choices=[('domain_expiry', 'Domain expiry'), ('ssl_expiry', 'SSL certificate expiry'), ('checklist_run_overdue', 'Checklist run overdue'), ('config_missing_primary_ip', 'Config item missing primary IP')], max_length=32),
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Webhook', max_length=200)),
                ('url', models.URLField()),
                ('secret_ciphertext', models.TextField(blank=True, default='')),
                ('verify_ssl', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], max_length=16)),
                ('ok', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='workflows.notification')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts', to='workflows.webhookendpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['organization', 'enabled', 'updated_at'], name='workflows_w_organiz_ea8d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['kind', 'ok', '-attempted_at'], name='workflows_n_kind_3562f0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['notification', 'kind', 'ok'], name='workflows_n_notific_69e7e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdeliveryattempt',
            constraint=models.UniqueConstraint(fields=('notification', 'kind', 'endpoint'), name='uniq_workflows_delivery_attempt'),
        ),
    ]
