# Generated by Django 5.1.6 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_alter_workflowrule_kind_webhookendpoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowrule",
            name="kind",
            field=models.CharField(
                choices=[
                    ("domain_expiry", "Domain expiry"),
                    ("ssl_expiry", "SSL certificate expiry"),
                    ("checklist_run_overdue", "Checklist run overdue"),
                    ("config_missing_primary_ip", "Config item missing primary IP"),
                    ("asset_missing_location", "Asset missing location"),
                    ("password_missing_url", "Password missing URL"),
                    ("password_rotation_due", "Password rotation due"),
                ],
                max_length=32,
            ),
        ),
    ]

