# Generated by Django 5.1.6 on 2026-02-14 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_organization_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.relationshiptype'),
        ),
    ]
