# Generated by Django 5.1.6 on 2026-02-14 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_alter_relationship_relationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable key used for API/export (e.g. 'warranty_expires').", max_length=64)),
                ('name', models.CharField(help_text="Human-friendly label (e.g. 'Warranty Expires').", max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('url', 'URL')], default='text', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('value_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.customfield')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='core.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['organization', 'content_type', 'sort_order', 'name'], name='core_custom_organiz_9b710c_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('organization', 'content_type', 'key'), name='uniq_core_customfield_org_ct_key'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['organization', 'content_type', 'object_id'], name='core_custom_organiz_fe28a9_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['organization', 'field'], name='core_custom_organiz_329cca_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('organization', 'field', 'content_type', 'object_id'), name='uniq_core_customfieldvalue_org_field_obj'),
        ),
    ]
