# Generated by Django 5.1.6 on 2026-02-15 00:00

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_customfield_customfieldvalue_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "model_key",
                    models.CharField(
                        choices=[
                            ("assets.asset", "Assets"),
                            ("assets.configurationitem", "Config Items"),
                            ("people.contact", "Contacts"),
                            ("core.location", "Locations"),
                            ("docsapp.document", "Docs"),
                            ("docsapp.documenttemplate", "Templates"),
                            ("secretsapp.passwordentry", "Passwords"),
                        ],
                        max_length=80,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="savedview",
            index=models.Index(fields=["organization", "model_key", "name"], name="core_savedv_organiz_2e2f40_idx"),
        ),
        migrations.AddConstraint(
            model_name="savedview",
            constraint=models.UniqueConstraint(
                fields=("organization", "model_key", "name"),
                name="uniq_core_savedview_org_key_name",
            ),
        ),
    ]

