# Generated by Django 5.1.6 on 2026-02-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_savedview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedview',
            new_name='core_savedv_organiz_f27cd3_idx',
            old_name='core_savedv_organiz_2e2f40_idx',
        ),
        migrations.AddField(
            model_name='note',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='note',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
