# Generated by Django 5.1.6 on 2026-02-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_savedv_organiz_2e2f40_idx_core_savedv_organiz_f27cd3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedview',
            name='model_key',
            field=models.CharField(choices=[('assets.asset', 'Assets'), ('assets.configurationitem', 'Config Items'), ('people.contact', 'Contacts'), ('core.location', 'Locations'), ('docsapp.document', 'Docs'), ('docsapp.documenttemplate', 'Templates'), ('secretsapp.passwordentry', 'Passwords'), ('netapp.domain', 'Domains'), ('netapp.sslcertificate', 'SSL Certificates')], max_length=80),
        ),
    ]
