# Generated by Django 5.1.6 on 2026-02-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_savedview_model_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customfield',
            name='uniq_core_customfield_org_ct_key',
        ),
    ]
