# Generated by Django 5.1.6 on 2026-02-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_remove_customfield_uniq_core_customfield_org_ct_key'),
        ('flexassets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='flexible_asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='flexassets.flexibleassettype'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['organization', 'content_type', 'flexible_asset_type', 'sort_order', 'name'], name='core_custom_organiz_d894cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('organization', 'content_type', 'flexible_asset_type', 'key'), name='uniq_core_customfield_org_ct_flex_key'),
        ),
    ]
