# Generated by Django 5.1.6 on 2026-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customfield_flexible_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='location',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'archived_at'], name='core_locati_organiz_73acdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_core_location_org_name_active'),
        ),
    ]
