# Generated by Django 5.1.6 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_location_unique_together_location_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="file_folders", to="core.organization"),
                ),
                (
                    "parent",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="core.filefolder"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization", "parent", "name"], name="idx_core_filefolder_tree"),
                    models.Index(fields=["organization", "archived_at"], name="idx_core_filefolder_archived"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "parent", "name"),
                        condition=Q(("archived_at__isnull", True)),
                        name="uniq_core_filefolder_org_parent_name_active",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="folder",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attachments", to="core.filefolder"),
        ),
        migrations.AddField(
            model_name="attachment",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="attachments", to="core.tag"),
        ),
    ]

