# Generated by Django 5.1.6 on 2026-02-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_attachmentsharelink_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('ip_allowlist', models.TextField(blank=True, default='', help_text='Comma-separated CIDRs/IPs.')),
                ('ip_blocklist', models.TextField(blank=True, default='', help_text='Comma-separated CIDRs/IPs.')),
                ('trust_x_forwarded_for', models.BooleanField(default=False)),
                ('trusted_proxy_cidrs', models.TextField(blank=True, default='', help_text='Comma-separated CIDRs/IPs.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
