# Generated by Django 5.1.6 on 2026-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_workerheartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="email_backend",
            field=models.CharField(blank=True, default="console", help_text="console|smtp|smtp+tls|smtp+ssl", max_length=32),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_from",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_source",
            field=models.CharField(
                choices=[("env", "Environment (.env)"), ("db", "Database (UI-configured)")],
                default="env",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_password_ciphertext",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_use_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_user",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]

