# Generated by Django 5.1.6 on 2026-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_systemsettings_email_backend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="cors_allowed_origins",
            field=models.TextField(blank=True, default="", help_text="Comma-separated origins (e.g. https://app.example.com)."),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="csrf_trusted_origins",
            field=models.TextField(blank=True, default="", help_text="Comma-separated origins (e.g. https://homeglue.example.com)."),
        ),
    ]

