# Generated by Django 5.1.6 on 2026-02-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_systemsettings_cors_csrf"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="allowed_hosts",
            field=models.TextField(blank=True, default="", help_text="Comma-separated hosts (mirrors HOMEGLUE_ALLOWED_HOSTS)."),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="reauth_ttl_seconds",
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_timeout_seconds",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="webhook_timeout_seconds",
            field=models.IntegerField(default=8),
        ),
    ]

