# Generated by Django 5.1.6 on 2026-02-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordentry',
            new_name='secretsapp__organiz_386b8c_idx',
            old_name='secrets_pw_org_name_idx',
        ),
    ]
