# Generated by Django 5.1.6 on 2026-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('secretsapp', '0002_rename_secrets_pw_org_name_idx_secretsapp__organiz_386b8c_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passwordentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['organization', 'archived_at'], name='secretsapp__organiz_533e41_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordentry',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_secrets_password_org_name_active'),
        ),
    ]
