# Generated by Django 5.1.6 on 2026-02-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('secretsapp', '0003_alter_passwordentry_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Only used when visibility=Shared.', related_name='shared_password_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_password_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='visibility',
            field=models.CharField(choices=[('org', 'Org (all members)'), ('admins', 'Admins only'), ('private', 'Private (creator only)'), ('shared', 'Shared (selected users)')], default='admins', max_length=16),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['organization', 'visibility'], name='secretsapp__organiz_87808b_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['organization', 'created_by'], name='secretsapp__organiz_2233ae_idx'),
        ),
    ]
