# Generated by Django 5.1.6 on 2026-02-15 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('secretsapp', '0004_passwordentry_allowed_users_passwordentry_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='passwordentry',
            name='uniq_secrets_password_org_name_active',
        ),
        migrations.AddField(
            model_name='passwordfolder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_folders', to='core.organization'),
        ),
        migrations.AddField(
            model_name='passwordfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='secretsapp.passwordfolder'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_entries', to='secretsapp.passwordfolder'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['organization', 'folder'], name='secretsapp__organiz_7913ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordentry',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'folder', 'name'), name='uniq_secrets_password_org_folder_name_active'),
        ),
        migrations.AddIndex(
            model_name='passwordfolder',
            index=models.Index(fields=['organization', 'parent', 'name'], name='secretsapp__organiz_43740e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordfolder',
            index=models.Index(fields=['organization', 'archived_at'], name='secretsapp__organiz_96c354_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'parent', 'name'), name='uniq_secrets_pwfolder_org_parent_name_active'),
        ),
    ]
