# Generated by Django 5.1.6 on 2026-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsapp', '0005_passwordfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='totp_algorithm',
            field=models.CharField(choices=[('SHA1', 'SHA1'), ('SHA256', 'SHA256'), ('SHA512', 'SHA512')], default='SHA1', max_length=10),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='totp_digits',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='totp_period',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='totp_secret_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
