# Generated by Django 5.1.6 on 2026-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_location_unique_together_location_archived_at_and_more"),
        ("secretsapp", "0006_passwordentry_totp_algorithm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordShareLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("token_prefix", models.CharField(blank=True, default="", max_length=12)),
                ("expires_at", models.DateTimeField()),
                ("one_time", models.BooleanField(default=False)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_password_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="password_share_links", to="core.organization")),
                ("password_entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="share_links", to="secretsapp.passwordentry")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization", "-created_at"], name="secretsapp__organiz_6e74ff_idx"),
                    models.Index(fields=["password_entry", "-created_at"], name="secretsapp__passwor_e22735_idx"),
                    models.Index(fields=["expires_at"], name="secretsapp__expires_2110a3_idx"),
                    models.Index(fields=["revoked_at"], name="secretsapp__revoked_1b182d_idx"),
                    models.Index(fields=["consumed_at"], name="secretsapp__consume_6609f7_idx"),
                ],
            },
        ),
    ]

