# Generated by Django 5.1.6 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretsapp", "0007_passwordsharelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordentry",
            name="last_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordentry",
            name="rotation_interval_days",
            field=models.IntegerField(default=0),
        ),
    ]

