# Generated by Django 5.1.6 on 2026-02-14 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('core', '0005_alter_relationship_relationship_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_ts_db3712_idx',
            old_name='audit_evt_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_model_912e1b_idx',
            old_name='audit_evt_model_pk_idx',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'ts'], name='audit_audit_organiz_a16f05_idx'),
        ),
    ]
