# Generated by Django 5.1.6 on 2026-02-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_audit_evt_ts_idx_audit_audit_ts_db3712_idx_and_more'),
        ('core', '0006_customfield_customfieldvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.organization'),
        ),
    ]
