# Generated by Django 5.1.6 on 2026-02-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='docsapp_doc_organiz_9b5b17_idx',
            old_name='docs_doc_org_title_idx',
        ),
    ]
