# Generated by Django 5.1.6 on 2026-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('docsapp', '0002_rename_docs_doc_org_title_idx_docsapp_doc_organiz_9b5b17_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'archived_at'], name='docsapp_doc_organiz_74bb39_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['organization', 'archived_at'], name='docsapp_doc_organiz_5f4942_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_docs_template_org_name_active'),
        ),
    ]
