# Generated by Django 5.1.6 on 2026-02-15 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('docsapp', '0005_document_flagged_at_document_flagged_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='docsapp.documentfolder')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docsapp.documentfolder'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'folder'], name='docsapp_doc_organiz_1a4a15_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['organization', 'parent', 'name'], name='docsapp_doc_organiz_38e13d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['organization', 'archived_at'], name='docsapp_doc_organiz_779d59_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'parent', 'name'), name='uniq_docs_docfolder_org_parent_name_active'),
        ),
    ]
