# Generated by Django 5.1.6 on 2026-02-16 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docsapp", "0006_documentfolder_document_folder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="review_state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("in_review", "In review"), ("approved", "Approved")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "document",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="docsapp.document"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_comments", to="core.organization"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "review_state"], name="docsapp_doc_organiz_5819c3_idx"),
        ),
        migrations.AddIndex(
            model_name="documentcomment",
            index=models.Index(fields=["organization", "document", "-created_at"], name="docsapp_doc_organiz_b9809d_idx"),
        ),
    ]
