# Generated by Django 5.1.6 on 2026-02-16 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_location_unique_together_location_archived_at_and_more"),
        ("docsapp", "0007_document_review_fields_and_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="review_state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("in_review", "In review"), ("approved", "Approved")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_document_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DocumentTemplateComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_template_comments", to="core.organization"),
                ),
                (
                    "template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="docsapp.documenttemplate"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(fields=["organization", "review_state"], name="docsapp_doc_organiz_5fd594_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttemplatecomment",
            index=models.Index(fields=["organization", "template", "-created_at"], name="docsapp_doc_organiz_1f7fd6_idx"),
        ),
    ]
