# Generated by Django 5.1.6 on 2026-02-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docsapp", "0008_documenttemplate_review_fields_and_comments"),
    ]

    operations = [
        # Intentionally empty: prior auto-generated rename migration became invalid after
        # we pinned index names in 0008 to match the state model.
    ]
