# Generated by Django 5.1.6 on 2026-02-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0009_rename_docsapp_doc_organiz_5fd594_idx_docsapp_doc_organiz_90cf48_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documenttemplate',
            new_name='docsapp_doc_organiz_90cf48_idx',
            old_name='docsapp_doc_organiz_5fd594_idx',
        ),
        migrations.RenameIndex(
            model_name='documenttemplatecomment',
            new_name='docsapp_doc_organiz_c8bc84_idx',
            old_name='docsapp_doc_organiz_1f7fd6_idx',
        ),
    ]
