# Generated by Django 5.1.6 on 2026-02-15 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='checklists', to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('is_done', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklist')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['organization', 'name'], name='checklists__organiz_08913d_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['organization', 'archived_at'], name='checklists__organiz_08183f_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['organization', '-updated_at'], name='checklists__organiz_5c4c95_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_checklists_checklist_org_name_active'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['organization', 'checklist', 'sort_order', 'id'], name='checklists__organiz_360deb_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['organization', 'is_done'], name='checklists__organiz_f4f225_idx'),
        ),
    ]
