# Generated by Django 5.1.6 on 2026-02-15 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('canceled', 'Canceled')], default='open', max_length=16)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_runs', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='checklists.checklist')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_runs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_runs', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('is_done', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='checklists.checklistitem')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_checklist_run_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_run_items', to='core.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklistrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='checklistrun',
            index=models.Index(fields=['organization', 'status', 'due_on'], name='checklists__organiz_412330_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrun',
            index=models.Index(fields=['organization', 'archived_at'], name='checklists__organiz_58dc48_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrun',
            index=models.Index(fields=['organization', 'checklist', '-updated_at'], name='checklists__organiz_81ec0b_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrunitem',
            index=models.Index(fields=['organization', 'run', 'sort_order', 'id'], name='checklists__organiz_06ae02_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrunitem',
            index=models.Index(fields=['organization', 'is_done'], name='checklists__organiz_b1ae24_idx'),
        ),
    ]
