# Generated by Django 5.1.6 on 2026-02-15 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklistrun_checklistrunitem_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrun',
            name='scheduled_for',
            field=models.DateField(blank=True, help_text='Scheduled date for runs created by a schedule.', null=True),
        ),
        migrations.CreateModel(
            name='ChecklistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Schedule name, e.g. Weekly backups review', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('every_days', models.IntegerField(default=7, help_text='Create a run every N days.')),
                ('due_days', models.IntegerField(blank=True, help_text='Due date offset in days (blank = no due date).', null=True)),
                ('next_run_on', models.DateField(help_text='Next scheduled run date.')),
                ('last_created_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_schedules', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='checklists.checklist')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_schedules', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='If set, this run was created by a recurring schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='checklists.checklistschedule'),
        ),
        migrations.AddIndex(
            model_name='checklistrun',
            index=models.Index(fields=['organization', 'schedule', 'scheduled_for'], name='checklists__organiz_ecb540_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistrun',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('schedule__isnull', False), ('scheduled_for__isnull', False)), fields=('organization', 'schedule', 'scheduled_for'), name='uniq_checklistrun_org_schedule_date_active'),
        ),
        migrations.AddIndex(
            model_name='checklistschedule',
            index=models.Index(fields=['organization', 'enabled', 'next_run_on'], name='checklists__organiz_8193c2_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistschedule',
            index=models.Index(fields=['organization', 'checklist', 'enabled'], name='checklists__organiz_3015d4_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistschedule',
            index=models.Index(fields=['organization', 'archived_at'], name='checklists__organiz_aa05de_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_checklists_schedule_org_name_active'),
        ),
    ]
