# Generated by Django 5.1.6 on 2026-02-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_savedview_model_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Proxmox', max_length=200)),
                ('base_url', models.URLField(help_text='e.g. https://pve.example.com:8006')),
                ('token_id', models.CharField(help_text='e.g. root@pam!homeglue', max_length=200)),
                ('token_secret_ciphertext', models.TextField(blank=True, default='')),
                ('verify_ssl', models.BooleanField(default=False, help_text='Disable for self-signed certs (not recommended).')),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_ok', models.BooleanField(default=False)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxmox_connections', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProxmoxGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(blank=True, default='', max_length=200)),
                ('vmid', models.IntegerField()),
                ('guest_type', models.CharField(choices=[('qemu', 'VM'), ('lxc', 'Container')], max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('cpu', models.FloatField(blank=True, null=True)),
                ('maxcpu', models.IntegerField(blank=True, null=True)),
                ('mem', models.BigIntegerField(blank=True, null=True)),
                ('maxmem', models.BigIntegerField(blank=True, null=True)),
                ('disk', models.BigIntegerField(blank=True, null=True)),
                ('maxdisk', models.BigIntegerField(blank=True, null=True)),
                ('uptime', models.BigIntegerField(blank=True, null=True)),
                ('ip_addrs', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('config_raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='integrations.proxmoxconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ProxmoxNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=200)),
                ('iface', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=64)),
                ('netmask', models.CharField(blank=True, default='', max_length=64)),
                ('gateway', models.CharField(blank=True, default='', max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='integrations.proxmoxconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ProxmoxNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('cpu', models.FloatField(blank=True, null=True)),
                ('maxcpu', models.IntegerField(blank=True, null=True)),
                ('mem', models.BigIntegerField(blank=True, null=True)),
                ('maxmem', models.BigIntegerField(blank=True, null=True)),
                ('disk', models.BigIntegerField(blank=True, null=True)),
                ('maxdisk', models.BigIntegerField(blank=True, null=True)),
                ('uptime', models.BigIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='integrations.proxmoxconnection')),
            ],
        ),
        migrations.AddIndex(
            model_name='proxmoxconnection',
            index=models.Index(fields=['organization', 'enabled', 'updated_at'], name='integration_organiz_06cfca_idx'),
        ),
        migrations.AddIndex(
            model_name='proxmoxguest',
            index=models.Index(fields=['connection', 'node'], name='integration_connect_484635_idx'),
        ),
        migrations.AddIndex(
            model_name='proxmoxguest',
            index=models.Index(fields=['connection', 'guest_type', 'vmid'], name='integration_connect_66a1da_idx'),
        ),
        migrations.AddIndex(
            model_name='proxmoxguest',
            index=models.Index(fields=['connection', 'name'], name='integration_connect_5e12e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proxmoxguest',
            unique_together={('connection', 'guest_type', 'vmid')},
        ),
        migrations.AddIndex(
            model_name='proxmoxnetwork',
            index=models.Index(fields=['connection', 'node'], name='integration_connect_5a5a41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proxmoxnetwork',
            unique_together={('connection', 'node', 'iface')},
        ),
        migrations.AddIndex(
            model_name='proxmoxnode',
            index=models.Index(fields=['connection', 'node'], name='integration_connect_403145_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proxmoxnode',
            unique_together={('connection', 'node')},
        ),
    ]
