# Generated by Django 5.1.6 on 2026-02-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_assets_asset_org_name_idx_assets_asse_organiz_16d854_idx_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxmoxguest',
            name='config_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxmox_guest', to='assets.configurationitem'),
        ),
    ]
