# Generated by Django 5.1.6 on 2026-02-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_proxmoxguest_config_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxmoxconnection',
            name='sync_interval_minutes',
            field=models.IntegerField(default=0, help_text='0 = manual only. Suggested: 15.'),
        ),
        migrations.CreateModel(
            name='ProxmoxCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='integrations.proxmoxconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ProxmoxStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('used', models.BigIntegerField(blank=True, null=True)),
                ('avail', models.BigIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='integrations.proxmoxconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['connection', 'node'], name='integration_connect_eeaf0f_idx')],
                'unique_together': {('connection', 'node', 'storage')},
            },
        ),
    ]
