# Generated by Django 5.1.6 on 2026-02-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_proxmoxconnection_sync_interval_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxmoxguest',
            name='ostype',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='proxmoxguest',
            name='proxmox_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proxmoxnode',
            name='status_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proxmoxnode',
            name='version_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProxmoxGuestIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('agent', 'Guest agent'), ('config', 'Config hint')], default='config', max_length=16)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_history', to='integrations.proxmoxguest')),
            ],
            options={
                'indexes': [models.Index(fields=['guest', 'last_seen_at'], name='integration_guest_i_c53fd5_idx')],
                'unique_together': {('guest', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='ProxmoxPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poolid', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, default='')),
                ('detail_raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='integrations.proxmoxconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['connection', 'poolid'], name='integration_connect_f8732e_idx')],
                'unique_together': {('connection', 'poolid')},
            },
        ),
        migrations.CreateModel(
            name='ProxmoxSdnSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=200)),
                ('vnet', models.CharField(blank=True, default='', max_length=200)),
                ('gateway', models.CharField(blank=True, default='', max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdn_subnets', to='integrations.proxmoxconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['connection', 'vnet'], name='integration_connect_24f640_idx')],
                'unique_together': {('connection', 'subnet')},
            },
        ),
        migrations.CreateModel(
            name='ProxmoxSdnVnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnet', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, default='', max_length=200)),
                ('alias', models.CharField(blank=True, default='', max_length=200)),
                ('tag', models.IntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdn_vnets', to='integrations.proxmoxconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['connection', 'zone'], name='integration_connect_30ac5f_idx')],
                'unique_together': {('connection', 'vnet')},
            },
        ),
        migrations.CreateModel(
            name='ProxmoxSdnZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdn_zones', to='integrations.proxmoxconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['connection', 'zone'], name='integration_connect_10be93_idx')],
                'unique_together': {('connection', 'zone')},
            },
        ),
    ]
