# Generated by Django 5.1.6 on 2026-02-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_proxmoxguest_ostype_proxmoxguest_proxmox_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxmoxguest',
            name='agent_hostname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proxmoxguest',
            name='agent_osinfo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proxmoxguest',
            name='pool',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
