# Generated by Django 5.1.6 on 2026-02-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0001_initial"),
        ("core", "0012_alter_location_unique_together_location_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False)),
                ("interval_hours", models.IntegerField(default=24, help_text="How often to schedule snapshots when enabled.")),
                ("retention_count", models.IntegerField(default=30, help_text="How many successful snapshots to keep.")),
                ("last_scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="backup_policy", to="core.organization"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["enabled", "next_run_at"], name="backups_bac_enabled_23eac1_idx"),
                ],
            },
        ),
    ]
