# Generated by Django 5.1.6 on 2026-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_backuppolicy"),
        ("core", "0012_alter_location_unique_together_location_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRestoreBundle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("file", models.FileField(upload_to="backups/restore/%Y/%m/%d/")),
                ("bytes", models.BigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(choices=[("uploaded", "Uploaded"), ("valid", "Valid"), ("invalid", "Invalid")], default="uploaded", max_length=16)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("media_extracted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="backup_restore_bundles", to="core.organization"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_backup_restore_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization", "status", "-created_at"], name="backups_bac_organiz_d6c30d_idx"),
                    models.Index(fields=["organization", "-created_at"], name="backups_bac_organiz_47fc05_idx"),
                ],
            },
        ),
    ]
