# Generated by Django 5.1.6 on 2026-02-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='people_cont_organiz_14b6be_idx',
            old_name='people_cont_org_lnf_idx',
        ),
    ]
