# Generated by Django 5.1.6 on 2026-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_unique_together_location_archived_at_and_more'),
        ('people', '0002_rename_people_cont_org_lnf_idx_people_cont_organiz_14b6be_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'archived_at'], name='people_cont_organiz_821a17_idx'),
        ),
    ]
